services:
  db:
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-air_quality}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
      args:
        APP_PORT: ${BACK_PORT:-8000} # Pass .env port to build
    image: air_quality_backend
    ports:
      - "127.0.0.1:${BACK_PORT:-3000}:${BACK_PORT:-3000}"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./AirQualityUCI.csv:${CSV_FILE_PATH:-/app/data/AirQualityUCI.csv}

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    image: air_quality_frontend
    ports:
      - "127.0.0.1:${FRONT_PORT:-5147}:80"
    env_file: .env
    depends_on:
      - back

volumes:
  db_data:
