@host = http://localhost:8000

### health Check
GET {{host}}/health
Content-Type: application/json
Accept: application/json


### filter endpoint
@parameter1=co_gt
@parameter2=no2_gt
@startDate=2004-03-01
@endDate=2004-03-31

POST {{host}}/filter
Content-Type: application/json

{
  "parameters": ["{{parameter1}}", "{{parameter2}}"],
  "startDate": "{{startDate}}",
  "endDate": "{{endDate}}"
}